- name: OSPF
  hosts: all
  gather_facts: True
  
  pre_tasks:
    - name: Rename hostanme
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'
        use: systemd

  roles: 
    - role: install_utils
    - role: enable_ip_forwarding
    - role: install_frr
      vars:
        router_id_enable: false  

